AppBundle\Entity\SfUser:
    type: entity
    table: sf_user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        email:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        password:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
